package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTestrecord<M extends BaseTestrecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setQuestionIds(java.lang.String questionIds) {
		set("questionIds", questionIds);
		return (M)this;
	}
	
	public java.lang.String getQuestionIds() {
		return getStr("questionIds");
	}

	public M setIsCorrect(java.lang.String isCorrect) {
		set("isCorrect", isCorrect);
		return (M)this;
	}
	
	public java.lang.String getIsCorrect() {
		return getStr("isCorrect");
	}

	public M setAnswers(java.lang.String answers) {
		set("answers", answers);
		return (M)this;
	}
	
	public java.lang.String getAnswers() {
		return getStr("answers");
	}

	public M setIsFinish(java.lang.Integer isFinish) {
		set("isFinish", isFinish);
		return (M)this;
	}
	
	public java.lang.Integer getIsFinish() {
		return getInt("isFinish");
	}

}
