package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWrongset<M extends BaseWrongset<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWrongset(java.lang.String wrongset) {
		set("wrongset", wrongset);
		return (M)this;
	}
	
	public java.lang.String getWrongset() {
		return getStr("wrongset");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setRecordId(java.lang.Integer recordId) {
		set("recordId", recordId);
		return (M)this;
	}
	
	public java.lang.Integer getRecordId() {
		return getInt("recordId");
	}

}
