package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseTestrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Testrecord extends BaseTestrecord<Testrecord> {
	public static final Testrecord dao = new Testrecord().dao();
}
