package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWrongset;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wrongset extends BaseWrongset<Wrongset> {
	public static final Wrongset dao = new Wrongset().dao();
}
